[global]
showWarningOnDirectExecution = false
developmentMode = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false

[server]
enableCORS = false
enableXsrfProtection = false
runOnSave = true
port = 8501

[theme]
primaryColor = "#007acc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1f2937"
